name: Eleventy Build Master
on:
  push:
    branches:
      - master
jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build 11ty
        run: |
          npm install
          npm run build
      - name: Save Commit Context
        uses: finnp/create-file-action@master
        env:
            FILE_NAME: "./docs/commit-info.json"
            FILE_DATA: ${{ toJson(github.event.commits) }}

      # Push built site files to S3 production bucket    
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'covid19.ca.gov'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: ./docs # only move built directory

      # Invalidate Cloudfront production distribution
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: 'EUZDM53N8V5KD'
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
