name: Staging deploy - AWS
on:
  push:
    branches:
      - staging

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allows you to call this workflow from another workflow -- see equity_deploy_staging.yml
  workflow_call:


jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
          submodules: true
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build 11ty
        run: |
          npm install
          npm run build

      # Push built site files to S3 production bucket    
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'staging.covid19.ca.gov'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: ./docs # only move built directory

      # Invalidate Cloudfront production distribution
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: 'E17SNE7QRMFCI3'
          PATHS: '/*'
          AWS_REGION: 'us-west-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
